name: test and publish

on:
  - push

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      max-parallel: 9
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
          - macos-latest
        python-version:
          - "3.7"
          - "3.8"
    steps:
      - uses: actions/checkout@v2
      - name: setup
        uses: actions/setup-python@v1.2.0
        with:
          python-version: ${{ matrix.python-version }}
        
      - name: install
        run: |
          pip install -e .
        
      - name: test
        run: |
          python tests/ga.py

  publish:
    runs-on: ubuntu-latest
    needs: test
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    steps:
      - uses: actions/checkout@v2.3.4
      - name: setup
        uses: actions/setup-python@v2
        with:
          python-version: "3.7"
      - name: build
        run: |
          python setup.py sdist
      - name: publish
        uses: pypa/gh-action-pypi-publish@v1.4.1
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        with:
          user: __token__
          password: ${{ secrets.PYPI_PASSWORD }}